# Production overrides
# Usage: docker compose -f compose.yml -f compose.prod.yml up -d
#
# Alternative (for deployment automation):
# Copy this to compose.override.yml: cp compose.prod.yml compose.override.yml
# Then run: docker compose up -d

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-production
      args:
        USER: www-data
        UID: 1000
        GID: 1000
    container_name: cs2inventory_php_prod
    working_dir: /var/www/html
    volumes:
      # Only mount directories that need to be writable at runtime
      - ./var/log:/var/www/html/var/log
      - ./var/data:/var/www/html/var/data
      - ./docker/php/php.prod.ini:/usr/local/etc/php/php.ini
    networks:
      - cs2inventory_network

  nginx:
    container_name: cs2inventory_nginx_prod
    ports:
      - "9003:80"
    volumes:
      # Only mount necessary directories for serving static files
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - cs2inventory_network
